services/urls.py
from django.urls import path,include
from tomlkit import document
from . import views


urlpatterns = [
    path("profile/<slug:slug>",views.display_profile, name="profile"),
    path("home/",views.home,name = "portal"),
    path("create/work/",views.WorkCreateView.as_view(),name = "create_work"),
    path("view/<slug:slug>/work/<int:pk>/member/",views.WorkDetailView.as_view(),name = "view_work"),
    path("manage/works/all/",views.ManageWorksView.as_view(),name = "manage_works"),
    path("manage/work/<int:pk>/update/<slug:slug>/",views.ManageWorksView.as_view(),name = "manage_works"),
    path("manage/progress/update/<int:pk>/member/",views.update_progress_by_member,name = "update_progress"),
]

zportal/urls.py
from services import views
from tomlkit import document
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.landingpage,name = "home"),
    path("registration/",include("social_django.urls",namespace = "social")),
    path("Logout/",auth_views.LogoutView.as_view(),name = "logout"),
    path('tinymce',include("tinymce.urls")),
    path('services/',include("services.urls"))
]
urlpatterns +=static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

services/models.py
from unittest.util import _MAX_LENGTH
from . choices import *
from django.db import models
from autoslug import AutoSlugField
from tinymce.models import HTMLField
from django.dispatch import receiver
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


from django.db.models.signals import post_save,m2m_changed


# Create your models here.


class Profile(models.Model):
    name = models.CharField(max_length=100)
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    email = models.EmailField()
    dept = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to = 'profile_pic/',blank = True)
    role = models.CharField(max_length = 200,choices = ROLE_CHOICES,blank = True)
    team = models.CharField(max_length = 200,choices = TEAM_CHOICES,blank = True)
    slug = AutoSlugField(populate_from='user',unique = True)
    Skillset = TaggableManager(blank=True)
    description = models.TextField()
    awards = models.CharField(max_length=500)
    def __str__(self):
        return self.user.email
class Work(models.Model):
    title = models.CharField(max_length = 200)
    description = HTMLField()
    date_of_creation = models.DateTimeField(auto_now_add = True)
    deadline = models.DateField(editable=True)
    created_by = models.ForeignKey(User,on_delete = models.CASCADE)
    assigned_to = models.ManyToManyField(User,related_name = "assigned")
    slug = AutoSlugField(populate_from='title',unique = True)
    def __str__(self):
        return self.title
class Progress(models.Model):
    assigned_work = models.ForeignKey(Work,on_delete = models.CASCADE)
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    progress = models.CharField(max_length = 200,choices = PROGRESS_CHOICES)
    reference = models.URLField(max_length = 300,help_text = "Upload Your Work Via Link",null = True,blank = True)
    def __str__(self):
        return self.assigned_work.title
    class Meta:
        verbose_name = "Progress"
        verbose_name_plural = "Progress"
@receiver(post_save,sender = User)
def create_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user = instance,role = "Member")
        instance.profile.save()
@receiver(post_save, sender = User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()
@receiver(m2m_changed,sender = Work.assigned_to.through)
def create_progress(sender,instance,**kwargs):
    for user in instance.assigned_to.all():
        progress = Progress(user = user,assigned_work = instance,progress = "ASSIGNED")
        progress.save()

    

services/forms.py
from .models import *
from django import forms

class WorkCreateForm(forms.ModelForm):
    class Meta:
        model = Work
        fields = ("title","description","deadline","assigned_to")
class ProgressUpdateForm(forms.ModelForm):
    class Meta:
        model = Progress
        fields = ('reference',)

services/views.py
import profile
from . forms import *
from . models import *
from . models import Profile
from . mixins import *
from django.http import Http404, HttpResponse
from django.views import generic
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required,user_passes_test


# Create your views here.
#Class Based Views

def display_profile(request, slug):
    p = get_object_or_404(Profile, slug=slug)
    if p:
        """ res = p[0]
        k = res.Skillset
        skills = k.split(',')
        res.Skillset=skills"""
        return render(request,"profile/index.html",{"res":p})

class WorkCreateView(UserPermissionMixin,SuccessMessageMixin,generic.CreateView):
    form_class = WorkCreateForm
    template_name = "services/CreateWork.html"
    success_url = reverse_lazy("home")
    success_message = "Work was successfully Assigned"
    def form_valid(self,form):
        form.instance.created_by = self.request.user
        super(WorkCreateView, self).form_valid(form)
        return redirect("home")
class ManageWorksView(LoginRequiredMixin,UserPermissionMixin,generic.ListView):
    model = Work
    fields = ['title','description','deadline','assigned_to']
    template_name = "services/ViewAllWorks.html"
    def queryset(self):
        return Work.objects.all().order_by('-date_of_creation')
    
class WorkDetailView(LoginRequiredMixin,generic.DetailView):
    model = Work
    fields = ['title','description','date_of_creation','deadline','created_by','assigned_to']
    template_name = "services/ViewWork.html"
    def get_object(self):
        work = super(WorkDetailView,self).get_object()
        if self.request.user in work.assigned_to.all() or self.request.user == work.created_by or self.request.user.is_superuser:
            return work
        raise Http404
class WorkUpdateView(LoginRequiredMixin,UserPermissionMixin,generic.UpdateView):
    model = Work
    slug_field = "Work.slug"
    fields = ['title','description','date_of_creation','deadline','created_by','assigned_to']
    template_name = "services/UpdateWork.html"
#Function Based Views
def home(request):
    progress = Progress.objects.filter(user = request.user,progress = "ASSIGNED").order_by('-assigned_work__date_of_creation')
    return render(request,"services/home.html",{"Progress":progress})
def landingpage(request):
    if request.user.is_authenticated:
        return redirect("portal")
    return render(request,"services/landing_page.html")
@login_required
def update_progress_by_member(request,pk):
    progress = get_object_or_404(Progress,pk=pk)
    if request.user in progress.assigned_work.assigned_to.all():
        progress_form = ProgressUpdateForm(request.FILES or None, request.POST or None,instance = progress)
        if progress_form.is_valid():
            progress_form.instance.progress = "APPROVAL PENDING"
            progress_form.save()
            messages.success(request,"Successfully Submitted for Approval")
            return redirect("portal")
        return render(request,'services/progress_update.html',{"progress":progress,"form":progress_form})
    else:
        messages.error(request,"Error Processing your Request")
        return redirect('portal')
    
        

services/templates/profile/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Profile</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">{{ res.name }}</span>
                <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{{ res.avatar }}" alt="..." /></span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#experience">Experience</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#education">Education</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#skills">Skills</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#interests">Interests</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#awards">Awards</a></li>
                </ul>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container-fluid p-0">
            <!-- About-->
            <section class="resume-section" id="about">
                <div class="resume-section-content">
                    <h1 class="mb-0">
                        {{res.name}}
                    </h1>
                    <div class="subheading mb-5">
                        {{ res.dept }} · 1234567890 ·
                        <a href="mailto:{{res.email}}">{{res.email}}</a>
                    </div>
                    <p class="lead mb-5">{{res.description}}</p>
                    <div class="social-icons">
                        <a class="social-icon" href="#!"><i class="fab fa-linkedin-in"></i></a>
                        <a class="social-icon" href="#!"><i class="fab fa-github"></i></a>
                        <a class="social-icon" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="social-icon" href="#!"><i class="fab fa-facebook-f"></i></a>
                    </div>
                </div>
            </section>
            <hr class="m-0" />
            <!-- Experience-->
            <section class="resume-section" id="experience">
                <div class="resume-section-content">
                    <h2 class="mb-5">Experience</h2>
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">Senior Web Developer</h3>
                            <div class="subheading mb-3">Intelitec Solutions</div>
                            <p>Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.</p>
                        </div>
                        <div class="flex-shrink-0"><span class="text-primary">March 2013 - Present</span></div>
                    </div>
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">Web Developer</h3>
                            <div class="subheading mb-3">Intelitec Solutions</div>
                            <p>Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.</p>
                        </div>
                        <div class="flex-shrink-0"><span class="text-primary">December 2011 - March 2013</span></div>
                    </div>
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">Junior Web Designer</h3>
                            <div class="subheading mb-3">Shout! Media Productions</div>
                            <p>Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration.</p>
                        </div>
                        <div class="flex-shrink-0"><span class="text-primary">July 2010 - December 2011</span></div>
                    </div>
                    <div class="d-flex flex-column flex-md-row justify-content-between">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">Web Design Intern</h3>
                            <div class="subheading mb-3">Shout! Media Productions</div>
                            <p>Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.</p>
                        </div>
                        <div class="flex-shrink-0"><span class="text-primary">September 2008 - June 2010</span></div>
                    </div>
                </div>
            </section>
            <hr class="m-0" />
            <!-- Education-->
            <section class="resume-section" id="education">
                <div class="resume-section-content">
                    <h2 class="mb-5">Education</h2>
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">University of Colorado Boulder</h3>
                            <div class="subheading mb-3">Bachelor of Science</div>
                            <div>Computer Science - Web Development Track</div>
                            <p>GPA: 3.23</p>
                        </div>
                        <div class="flex-shrink-0"><span class="text-primary">August 2006 - May 2010</span></div>
                    </div>
                    <div class="d-flex flex-column flex-md-row justify-content-between">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">James Buchanan High School</h3>
                            <div class="subheading mb-3">Technology Magnet Program</div>
                            <p>GPA: 3.56</p>
                        </div>
                        <div class="flex-shrink-0"><span class="text-primary">August 2002 - May 2006</span></div>
                    </div>
                </div>
            </section>
            <hr class="m-0" />
            <!-- Skills-->
            <section class="resume-section" id="skills">
                <div class="resume-section-content">
                    <h2 class="mb-5">Skills</h2>
                    <div class="subheading mb-3">Programming Languages & Tools</div>
                    {{ res.tags.all }}
                   <ul>
                   {% for i in res.Skillset.all %}
                   <span class="badge badge-secondary">{{ i.name }}</span>
                   {% endfor %}
                   </ul>
                    <div class="subheading mb-3">Workflow</div>
                    <ul class="fa-ul mb-0">
                        <li>
                            <span class="fa-li"><i class="fas fa-check"></i></span>
                            Mobile-First, Responsive Design
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-check"></i></span>
                            Cross Browser Testing & Debugging
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-check"></i></span>
                            Cross Functional Teams
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-check"></i></span>
                            Agile Development & Scrum
                        </li>
                    </ul>
                </div>
            </section>
            <hr class="m-0" />
            <!-- Interests-->
            <section class="resume-section" id="interests">
                <div class="resume-section-content">
                    <h2 class="mb-5">Interests</h2>
                    <p>Apart from being a web developer, I enjoy most of my time being outdoors. In the winter, I am an avid skier and novice ice climber. During the warmer months here in Colorado, I enjoy mountain biking, free climbing, and kayaking.</p>
                    <p class="mb-0">When forced indoors, I follow a number of sci-fi and fantasy genre movies and television shows, I am an aspiring chef, and I spend a large amount of my free time exploring the latest technology advancements in the front-end web development world.</p>
                </div>
            </section>
            <hr class="m-0" />
            <!-- Awards-->
            <section class="resume-section" id="awards">
                <div class="resume-section-content">
                    <h2 class="mb-5">Awards & Certifications</h2>
                    <ul class="fa-ul mb-0">
                        <li>
                            <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                            Google Analytics Certified Developer
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                            Mobile Web Specialist - Google Certification
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                            1
                            <sup>st</sup>
                            Place - University of Colorado Boulder - Emerging Tech Competition 2009
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                            1
                            <sup>st</sup>
                            Place - University of Colorado Boulder - Adobe Creative Jam 2008 (UI Design Category)
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                            2
                            <sup>nd</sup>
                            Place - University of Colorado Boulder - Emerging Tech Competition 2008
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                            1
                            <sup>st</sup>
                            Place - James Buchanan High School - Hackathon 2006
                        </li>
                        <li>
                            <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                            3
                            <sup>rd</sup>
                            Place - James Buchanan High School - Hackathon 2005
                        </li>
                    </ul>
                </div>
            </section>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

services/templates/services/CreateWork.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class = "container">
    <h1 class = "text-center">Assign Work</h1>
    <hr/>
    <form method = "POST" enctype = "multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <div class = "d-inline-block py-2">
            <button class = "btn btn-outline-success" type = "submit">Assign</button>
        </div>
    </form>
</div>
<script>
    $(document).ready(function() { 
        $(function () {
            $('#id_deadline').datepicker({ dateFormat: 'yy-mm-dd' });
        });
    })
  </script>
{% endblock %}

services/templates/services/ViewAllWorks.html
{% extends 'base.html' %}
{% block content %}
<div class = "container">
    <h1 class = "text-center">Manage Works</h1>
    <hr/>
    {% for work in object_list %}
    {% endfor %}
</div>
{% endblock %}

services/templates/services/ViewWork.html
{% extends 'base.html' %}
{% block content %}
<div class = "container">
    <h1 class = "text-center">{{work.title}}</h1>
    <hr/>
    <p>Description</p>
    <div class = "content-container container-fluid alert alert-secondary  overflow-auto">
        {{work.media}}
        {{work.description|safe}}
    </div>
    <p>Assigned To</p>
    <ul class="list-group">
        {% for user in work.assigned_to.all %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{user.username}}
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

services/templates/services/home.html
{% extends 'base.html' %}
{% block content %}
<div class = "container">
    <h1 class = "text-center">Your Tasks</h1>
    <hr/>
    <div class = "row">
        {% for progress in Progress %}
        <div class = "col-md-4">
            <div class="card text-white bg-secondary mb-3" style="margin-bottom:20px;">
                <div class="card-body">
                  <h4 class="card-title">{{progress.assigned_work.title}}</h4>
                  <h6 class="card-subtitle mb-2 text-muted">Deadline: {{progress.assigned_work.deadline}}</h6>
                  <hr/>
                  <p class = "card-text">Assigned By : {{progress.assigned_work.created_by.profile.role}} {% if progress.assigned_work.created_by.profile.team %}of {{progress.assigned_work.created_by.profile.team}}{% endif %}</p>
                  <div class = "d-inline-block py-2">
                    <a class="btn btn-secondary" href = "{% url 'view_work' progress.assigned_work.slug progress.assigned_work.id %}" type="button" style="margin-bottom:10px;background: linear-gradient(146deg, #30E8BF, #FF8235);">View Work</a>
                    <a class="btn btn-secondary" href = "{% url 'update_progress' progress.id %}" type="button" style="margin-bottom:10px;background: linear-gradient(146deg, #30E8BF, #FF8235);">Update Progress</a>
                  </div>
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

services/templates/services/landing_page.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container">
  <div class="row" style="margin-top: 100px">
    <div class="col-md-6" style="padding: 50px">
        <div class="intro">
            <h1 class="text-center">ZWork</h1>
            <p class="text-center"><span class="by">by</span> <a href="#">ZBC VITC</a> | <span class="date text-muted">Last Updated On: Sept 8th, 2016 </span></p>
        </div>
        <div class="text">
            <p>Sed lobortis mi. Suspendisse vel placerat ligula. <span style="text-decoration: underline;">Vivamus</span> ac sem lac. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>
            <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac lacus. <strong>Ut vehicula rhoncus</strong> elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit <em>pulvinar dict</em> vel in justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>
        </div>
        <a
        href="{% url 'social:begin' 'google-oauth2' %}"
        class="btn btn-grad-1"
      >
        <img
          src="{% static 'Google.png' %}"
          alt="Gary Simon Avatar"
          height="30"
          width="30"
        />
        <span>Login with Google</span>
      </a>
    </div>
    <div class="col-md-6">
        <lottie-player src="https://assets1.lottiefiles.com/packages/lf20_SuD7G5.json"  background="transparent"  speed="1"  style="width: auto; height: auto;"  loop  autoplay></lottie-player>
    </div>
    </div>
</div>
{% endblock %}

services/templates/services/progress_update.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class = "container">
    <h1 class = "text-center">{{progress.assigned_work.title}}</h1>
    <hr/>
    <p>Description</p>
    <div class = "content-container container-fluid alert alert-secondary  overflow-auto">
        {{progress.assigned_work.media}}
        {{progress.assigned_work.description|safe}}
    </div>
    <form method = "POST" enctype = "multipart/form-data">
        {{form|crispy}}
        <div class = "d-inline-block py-2">
            {% csrf_token %}
            <button class = "btn btn-outline-secondary" style =  "color:white;" type = "submit">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

zportal/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link  href = "{% static 'css/Article-Clean.css' %}" rel = "stylesheet">
    <link  href = "{% static 'css/bootstrap.css' %}" rel = "stylesheet">
    <link href='https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/ui-lightness/jquery-ui.css' rel='stylesheet'>
    <link  href = "{% static 'css/custom.css' %}" rel = "stylesheet">
    

    <title>Z Work</title>
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-transparent " style = "margin-bottom:30px;">
            <div class="container">
              <a class="navbar-brand" href="{% url 'home' %}">Z Work</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
          
              <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav ms-auto">
                  {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="#">Dashboard</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'profile' user.profile.slug %}">Profile</a>
                    </li>
                    {% if user.is_superuser or user.profile.role == "President" %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'create_work' %}">Assign a New Work</a>
                        <a class="dropdown-item" href="{% url 'manage_works' %}">Manage Works</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                      </div>
                    </li>
                    {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% endif %}
                  {% else %}
                  
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
    </header>
    <div class = "container">
        {% include 'messages.html' %}
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
  </body>
</html>

zportal/templates/messages.html
{% for message in messages %}
{% if forloop.last %}
<div class="container-fluid py-2" id = 'message' style = "display:none;">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close" id = "custom">
    </button>
    <div class = "text-center">
      {{message}}
    </div>
  </div>
</div>
{% endif %}
{% endfor %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
{% for message in messages %}
<script>
$(message)
    .css('opacity', 0)
    .slideDown('slow')
    .animate(
      { opacity: 1 },
      { queue: false, duration: 'slow' }
);
$('.alert').click(function(){
$(message)
  $(message).animate({height:0, opacity: 0}, 2000);
});
 window.setTimeout(function() {
      $("#message").slideUp(500, function() {
          $(this).remove();
      });
  }, 6000);
</script>
{% endfor %}